## PyTorch Book Tutorial PlayGround

In [2]:
!pip install torch


In [1]:
import torch

In [2]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [3]:
torch.rand(1).item()

0.9972826838493347

In [4]:
cpu = torch.rand(1)
cpu.device

device(type='cpu')

In [5]:
gpu = cpu.to('cuda')
gpu.device

device(type='cuda', index=0)

In [6]:
torch.rand(2, 2).max()

tensor(0.9047)

In [8]:
tensor = torch.rand(2, 2).max().item()

In [10]:
long_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])

In [11]:
long_tensor.type()

'torch.LongTensor'

In [12]:
float_tensor = long_tensor.to(dtype=torch.float32)

In [13]:
float_tensor.type()

'torch.FloatTensor'

In [15]:
random_tensor = torch.rand(2,2)
random_tensor.log2()

tensor([[-3.1055, -6.3813],
        [-2.4650, -1.4983]])

In [16]:
random_tensor.log2_()

tensor([[-3.1055, -6.3813],
        [-2.4650, -1.4983]])

In [17]:
flat_tensor = torch.rand(784)
viewed_tensor = flat_tensor.view(1, 28, 28)
viewed_tensor.shape


torch.Size([1, 28, 28])

In [18]:
reshaped_tensor = flat_tensor.reshape(1, 28, 28)
reshaped_tensor.shape

torch.Size([1, 28, 28])

In [19]:
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2, 0, 1)
chw_tensor.shape

torch.Size([3, 640, 480])