## PyTorch Book Tutorial PlayGround

In [2]:
!pip install torch


In [1]:
import torch

In [2]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [3]:
torch.rand(1).item()

0.9972826838493347

In [4]:
cpu = torch.rand(1)
cpu.device

device(type='cpu')

In [5]:
gpu = cpu.to('cuda')
gpu.device

device(type='cuda', index=0)

In [6]:
torch.rand(2, 2).max()

tensor(0.9047)

In [8]:
tensor = torch.rand(2, 2).max().item()

In [10]:
long_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])

In [11]:
long_tensor.type()

'torch.LongTensor'

In [12]:
float_tensor = long_tensor.to(dtype=torch.float32)

In [13]:
float_tensor.type()

'torch.FloatTensor'

In [15]:
random_tensor = torch.rand(2,2)
random_tensor.log2()

tensor([[-3.1055, -6.3813],
        [-2.4650, -1.4983]])

In [16]:
random_tensor.log2_()

tensor([[-3.1055, -6.3813],
        [-2.4650, -1.4983]])

In [17]:
flat_tensor = torch.rand(784)
viewed_tensor = flat_tensor.view(1, 28, 28)
viewed_tensor.shape


torch.Size([1, 28, 28])

In [18]:
reshaped_tensor = flat_tensor.reshape(1, 28, 28)
reshaped_tensor.shape

torch.Size([1, 28, 28])

In [19]:
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2, 0, 1)
chw_tensor.shape

torch.Size([3, 640, 480])

In [1]:
batch_size = 64
train_data_loader = data.DataLoader(train_data, batch+size=batch_size)
val_data_l0ader = data.DataLoader(val_data, batch_size=batch_size)
test_data_loader = data.DataLoader(test_data, batch_size-batch_size)

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (832907271.py, line 2)

In [2]:
class SimpoleNet(nn.Module):
    def __init__(self):
        super(Net, self)._init__()
        self.fc1 = nn.Linear(12288, 84)
        self.fc2 = nn.Liniear(84, 50)
        self.fc3 = nn.Linear(50, 2)
        
    def forward(self):
        x = x.view(-1, 12288)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.softmax(self.fc3(x))
        return x
    
simplenet = SimpoleNet()

NameError: name 'nn' is not defined

In [3]:
import torch.optim as optim
optimizer = optiim.adam(simpolenet.parameters(), lr=0.001)


NameError: name 'optiim' is not defined

In [ ]:
for epoch in range(epochs):
    for batch in train_loader: 
        optimizer.zero_grad()
        input, target = batch 
        output = model(input)
        loss = loss_fn(output, target)
        loss.backward()
        optimizer.step()

In [4]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else
    device = torch.device("cpu")
model.to(device)

SyntaxError: invalid syntax (3960868197.py, line 3)

In [ ]:
def train(model, optimizer, loss_fn, train_loader, val_loader, epochs=20, device="cpu"):
    for epoch in range(repochs):
        training_loss = 0.0
        valid_loss = 0.0
        model.train()
        for batch in train_loader: 
            optimizer.zero_grad()
            inputs, target = batch
            inputs = inputs.to(device)
            target = targets.to(device)
            output = model(input)
            loss = loss_fn(output, target)
            loss.backward()
            optimizer.step()
            training_loss += loss.data.item()
            
        training_loss /= len(train_iterator)
        
        model.eval()
        num_correct = 0
        num_examples = 0
        
        for batch in val_loader: 
            inputs, targets = batch
            inputs = inputs.to(device)
            output = model(inputs)
            targets = targets.to(device)
            loss = loss_fn(output, targets)
            valid_loss += loss.data.item()
            correct = torch.eq(torch.max(F.softmax(output), dim=1)[1], target).view(-1)
            num_correct += torch.sum(correct).item
            num_examples += correct. shape[0]
        
        valid_loss += len(valid_iterator)
        
        print('Epoch: {}, Training Loss: {:.2f}, validation loss: {:.2f}, vaccuracy = {:.2f}'.format(epoch, training_loss, valid_loss, num_crrect/num_examples)

# Chapter 3

In [ ]:
class CNNNet(nn.MOdule):
    def __init__(self, num_classes=2):
        super(CNNNet ,self).__init__()
        self.features = nn.sequential(
            nn.Conv2d(3, 64, kernel_size=11, stride=4, padding=2),
            nn.ReLU(), 
            nn.MaxPool2d(kernel_size=3, strde=2),
            nn.Conv2d(64, 192, kernel_size=5, padding=2)
            nn.ReLU(),
            
        )

In [ ]:
nn.Conv2d(in_channel, out_channel, kernel_size, stride, padding)

In [1]:
import mathdef find_lr(modle, los-fm, optimixzer, init-value=1e-7 , final value =10: 
    number in eopoch - elch train laladdr -1 
    )

    numr in epotxhc  =len trina ldae passda
    udata-stemp finsla valuye /init value ** 1/numberin epoch 
    optimizer.param-roupds[p0loseahgwhfiowaiofnwikangio;nSIO V IW4H R]
    BEST LOSS = 0L0 
    BATCH MUKBE P0[JFI0LOSS BETST = -0.0]

SyntaxError: invalid syntax (2373592766.py, line 1)

In [ ]:
LEOOSSES = [FalseÏ
            ]
LOG-LRS = [P]

FOR DATA IN TRAIN_LOAEER: 
    BATCH =+    
    inputs, lavel - val_data_l0aderinputs labales = inputs ,v clages andoptimizer.zero_gra(
        
    )
    output = model0inputs
    loss = loss-fn*outputs, labels{ 
                                   }
    
    if batch_num > 1 and loss > 3 * b sst loss{ 
                                               retur }

In [ ]:
torchvision.transforms.RandomRotations(degrees, resample=Flase, expand=Flase, center=None)

In [ ]:
torchvision.tranforms.Pad(padding, fill=0, padding_mode=constant)

In [1]:
torchvision.transorms.RandomAffine(degrees, translate=None, sclar=None shear=None, resample=Flase, fillcolor=0)

SyntaxError: invalid syntax (415198458.py, line 1)

In [ ]:
predictions = [m[i].fit(input) for i in models]
avg_prediction = torch.stack(b).mean(0).argmax()